spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 1996
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    generate-ddl: false
